CREATE TABLE IF NOT EXISTS users (
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday date    NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id integer PRIMARY KEY,
    name   varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS genres (
    genre_id integer PRIMARY KEY,
    name     varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship_statuses (
    status_id integer PRIMARY KEY,
    name      varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar NOT NULL,
    description  varchar(200),
    release_date date    NOT NULL,
    duration     integer NOT NULL,
    mpa_id       integer REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genres (
    genre_id INTEGER REFERENCES genres (genre_id) ON DELETE CASCADE,
    film_id  BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
    requester_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    addressee_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    status_id INTEGER NOT NULL REFERENCES friendship_statuses (status_id),
    PRIMARY KEY (requester_id, addressee_id)
);

CREATE TABLE IF NOT EXISTS directors (
    director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS film_directors (
    film_id BIGINT REFERENCES films (film_id) ON DELETE CASCADE,
    director_id INTEGER REFERENCES directors (director_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
);

CREATE TABLE IF NOT EXISTS reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(5000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    film_id BIGINT NOT NULL REFERENCES films(film_id) ON DELETE CASCADE,
    useful INTEGER DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS review_likes (
    review_id BIGINT NOT NULL REFERENCES reviews(review_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
);