CREATE TABLE IF NOT EXISTS users
(
    user_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar NOT NULL,
    login    varchar NOT NULL,
    name     varchar,
    birthday date    NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id integer PRIMARY KEY,
    name   varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id integer PRIMARY KEY,
    name     varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship_statuses
(
    status_id integer PRIMARY KEY,
    name      varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         varchar NOT NULL,
    description  varchar(200),
    release_date date    NOT NULL,
    duration     integer NOT NULL,
    mpa_id       integer REFERENCES mpa (mpa_id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    genre_id INTEGER REFERENCES genres (genre_id),
    film_id  BIGINT REFERENCES films (film_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id BIGINT REFERENCES films (film_id),
    user_id BIGINT REFERENCES users (user_id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friendship
(
    requester_id BIGINT REFERENCES users (user_id),
    addressee_id BIGINT REFERENCES users (user_id),
    status_id INTEGER NOT NULL REFERENCES friendship_statuses (status_id),
    PRIMARY KEY (requester_id, addressee_id)
);